name: Deploy to dev

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    name: Deploying everything to dev cluster
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -i ~/ssh_key ubuntu@54.159.50.9 -o StrictHostKeyChecking=yes << 'EOF'
            sudo -i
            cd playing-with-prisma/
            git pull origin main

            export PATH=/root/.nvm/versions/node/v24.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

            npm install -g pnpm
            pnpm install
            pnpm run build

            pm2 restart frontend
            pm2 restart http-server
            pm2 restart ws-server
          EOF
