name: Deploy to dev
on:
  push:
      branches: [ main ]

  jobs:
    redeploy:
      runs-on: ubuntu@latest
      name: Deploying everything to dev cluster
      steps:
        - run : | 
            echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
            mkdir -p /home/runner/.ssh
            ls /home/runner/.ssh
            touch /home/runner/.ssh/known_hosts
            echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
            chmod 700 /home/runner/ssh_key
            ssh -i ~/ssh_key root@54.159.50.9 -t "cd playing-with-prisma/ && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart frontend && pm2 restart http-server && pm2 restart ws-server"

